# Generated by Django 2.2.8 on 2019-12-10 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='title',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='title',
        ),
    ]
