# Generated by Django 2.2.8 on 2019-12-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20191217_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='writer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='writer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='skilltalk',
            name='writer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='talk',
            name='writer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='content',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='content',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='skilltalk',
            name='content',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='talk',
            name='content',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
