# Generated by Django 2.2.8 on 2019-12-17 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20191217_1803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='algorithm',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='skilltalk',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='talk',
            options={'ordering': ['-id']},
        ),
    ]
