# Generated by Django 2.2.9 on 2019-12-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_algorithmcomment_projectscomment_skilltalkcomment_talkcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithmcomment',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='projectscomment',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='skilltalkcomment',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='talkcomment',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
