# Generated by Django 2.2.9 on 2019-12-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20191219_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithmcomment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='projectscomment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='skilltalkcomment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='talkcomment',
            name='image',
        ),
        migrations.AddField(
            model_name='algorithm',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='skilltalk',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='talk',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
