# Generated by Django 2.2.9 on 2019-12-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20191219_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='skilltalk',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='talk',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
