# Generated by Django 2.2.9 on 2019-12-23 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191217_1104'),
        ('posts', '0012_auto_20191219_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='algorithm_likes', to='users.User'),
        ),
        migrations.AddField(
            model_name='projects',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='project_likes', to='users.User'),
        ),
        migrations.AddField(
            model_name='skilltalk',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='skill_talk', to='users.User'),
        ),
        migrations.AddField(
            model_name='talk',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='talk_likes', to='users.User'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='algorithm', to='users.User'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='users.User'),
        ),
        migrations.AlterField(
            model_name='skilltalk',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skilltalk', to='users.User'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='talk', to='users.User'),
        ),
    ]
