# Generated by Django 2.2.9 on 2019-12-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20191223_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltalk',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='skill_likes', to='users.User'),
        ),
    ]
