# Generated by Django 2.2.9 on 2019-12-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20191223_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='algorithm_likes', to='users.User'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='project_likes', to='users.User'),
        ),
        migrations.AlterField(
            model_name='skilltalk',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='skill_likes', to='users.User'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='talk_likes', to='users.User'),
        ),
    ]
