# Generated by Django 2.2.8 on 2019-12-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_ay', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
