version: '3'

services:
  db:
    image: postgres
  redis:
    image: redis
  django:
    build: .
    ports:
      - "8000:8000"
    command:
      - python3
      - manage.py
      - runserver
      - 0.0.0.0:8000
    volumes:
      - .:/code
    depends_on:
      - db

