version: '3'

services:
  db:
    image: mysql
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'devel_db'
       MYSQL_USER: 'devel_db'
       MYSQL_PASSWORD: 'myroot'
       MYSQL_ROOT_PASSWORD: 'myroot'
  web:
    build: .
    command: python manage.py runserver
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db