version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./docker/data:/var/lib/postgresql/data

  django:
    build: .
    ports:
      - "8000:8000"
    command:
      - python3
      - manage.py
      - runserver
      # - python3 manage.py runserver
    volumes:
      - .:/code
    depends_on:
      - db



#       version: '3'

# services:
#   db:
#     image: mysql:5.7
#     ports:
#       - '3306:3306'
#     environment:
#        MYSQL_DATABASE: 'devel_db'
#        MYSQL_USER: 'devel_db'
#        MYSQL_PASSWORD: 'myroot'
#        MYSQL_ROOT_PASSWORD: 'myroot'
#   web:
#     build: .
#     command: python3 manage.py runserver
#     volumes:
      
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db


