# Generated by Django 2.2.9 on 2020-01-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_room_roommessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
