# Generated by Django 2.2.9 on 2020-01-14 06:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20200114_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommessage',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
