# Generated by Django 2.2.9 on 2020-01-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20200114_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommessage',
            name='label',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
